global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'auth'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth:5000']

  - job_name: 'data-layer-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['data-layer-api:5000']
