frontend:
  image: frontend
  port: 80
  nodePort: 30080

auth:
  image: auth
  imagePullPolicy: Never
  replicas: 1
  port: 5000
  nodePort: 30084
  dbApiUrl: "http://data-layer-api:5000"

backend:
  replicas: 1
  image: backend
  imagePullPolicy: Never
  port: 5000
  nodePort: 30085
  dbApiUrl: "http://data-layer-api:5000"



mongo:
  image: mongo:6
  port: 27017
  storage: 1Gi

adminer:
  image: adminer
  port: 8080
  nodePort: 30081

portainer:
  image: portainer/portainer-ce
  port: 9000
  nodePort: 30082

dataLayer:
  image: data-layer-api
  imagePullPolicy: Never
  port: 5000
  replicas: 1
  mongoUrl: "mongodb://database:27017/cloud_app"